Hospital Readmission

In [10]:
import pandas as pd

In [11]:
df=pd.read_csv("Downloads/Hospital Patient .csv")
df

,Patient_ID,Age,Gender,Condition,Medication,Admission_Date,Discharge_Date,Patient_State,Year_of_Admission,Length_of_Stay,Readmission,Outcome,Satisfaction,Insurance_Claimed,Total_Cost
0,1,45,Female,Heart Disease,Angioplasty,07-02-2024,12-02-2024,Kerala,2024,5,No,Recovered,4,Yes,15000
1,2,60,Male,Diabetes,Insulin Therapy,11-03-2023,14-03-2023,Goa,2023,3,Yes,Stable,3,No,2000
2,3,32,Female,Fractured Arm,X-Ray and Splint,02-01-2025,03-01-2025,Maharastra,2025,1,No,Recovered,5,Yes,500
3,4,75,Male,Stroke,CT Scan and Medication,30-12-2023,06-01-2024,Manipur,2023,7,Yes,Stable,2,No,10000
4,5,50,Female,Cancer,Surgery and Chemotherapy,10-05-2022,20-05-2022,Mizoram,2022,10,No,Recovered,4,No,25000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,980,68,Male,Hypertension,Medication and Counseling,28-02-2023,09-05-2023,Sikkim,2023,70,No,Stable,4,Yes,1000
980,981,45,Female,Appendicitis,Appendectomy,28-02-2024,10-05-2024,Andhra Pradesh,2024,72,No,Recovered,3,No,8000
981,982,40,Male,Fractured Leg,Cast and Physical Therapy,20-02-2025,03-05-2025,Puducherry,2025,72,No,Recovered,4,No,3000
982,983,78,Female,Heart Attack,Cardiac Catheterization,07-09-2024,20-11-2024,Punjab,2024,74,Yes,Stable,2,Yes,18000
983,984,25,Male,Allergic Reaction,Epinephrine Injection,30-11-2022,06-02-2023,Kerala,2022,68,No,Recovered,5,No,100

In [12]:
df.head()

,Patient_ID,Age,Gender,Condition,Medication,Admission_Date,Discharge_Date,Patient_State,Year_of_Admission,Length_of_Stay,Readmission,Outcome,Satisfaction,Insurance_Claimed,Total_Cost
0,1,45,Female,Heart Disease,Angioplasty,07-02-2024,12-02-2024,Kerala,2024,5,No,Recovered,4,Yes,15000
1,2,60,Male,Diabetes,Insulin Therapy,11-03-2023,14-03-2023,Goa,2023,3,Yes,Stable,3,No,2000
2,3,32,Female,Fractured Arm,X-Ray and Splint,02-01-2025,03-01-2025,Maharastra,2025,1,No,Recovered,5,Yes,500
3,4,75,Male,Stroke,CT Scan and Medication,30-12-2023,06-01-2024,Manipur,2023,7,Yes,Stable,2,No,10000
4,5,50,Female,Cancer,Surgery and Chemotherapy,10-05-2022,20-05-2022,Mizoram,2022,10,No,Recovered,4,No,25000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         984 non-null    int64
 1   Age                984 non-null    int64
 2   Gender             984 non-null    object
 3   Condition          984 non-null    object
 4   Medication         984 non-null    object
 5   Admission_Date     984 non-null    object
 6   Discharge_Date     984 non-null    object
 7   Patient_State      984 non-null    object
 8   Year_of_Admission  984 non-null    int64
 9   Length_of_Stay     984 non-null    int64
 10  Readmission        984 non-null    object
 11  Outcome            984 non-null    object
 12  Satisfaction       984 non-null    int64
 13  Insurance_Claimed  984 non-null    object
 14  Total_Cost         984 non-null    int64
dtypes: int64(6), object(9)
memory usage: 115.4+ KB

In [14]:
df.describe()

,Patient_ID,Age,Year_of_Admission,Length_of_Stay,Satisfaction,Total_Cost
count,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000
mean,492.500000,53.754065,2023.460366,37.663618,3.598577,8367.479675
std,284.200633,14.941135,1.106926,19.595805,0.883002,7761.990976
min,1.000000,25.000000,2022.000000,1.000000,2.000000,100.000000
25%,246.750000,45.000000,2022.000000,21.000000,3.000000,1000.000000
50%,492.500000,55.000000,2023.000000,38.000000,4.000000,6000.000000
75%,738.250000,65.000000,2024.000000,54.250000,4.000000,15000.000000
max,984.000000,78.000000,2025.000000,76.000000,5.000000,25000.000000

In [16]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
df

,patient_id,age,gender,condition,medication,admission_date,discharge_date,patient_state,year_of_admission,length_of_stay,readmission,outcome,satisfaction,insurance_claimed,total_cost
0,1,45,Female,Heart Disease,Angioplasty,07-02-2024,12-02-2024,Kerala,2024,5,No,Recovered,4,Yes,15000
1,2,60,Male,Diabetes,Insulin Therapy,11-03-2023,14-03-2023,Goa,2023,3,Yes,Stable,3,No,2000
2,3,32,Female,Fractured Arm,X-Ray and Splint,02-01-2025,03-01-2025,Maharastra,2025,1,No,Recovered,5,Yes,500
3,4,75,Male,Stroke,CT Scan and Medication,30-12-2023,06-01-2024,Manipur,2023,7,Yes,Stable,2,No,10000
4,5,50,Female,Cancer,Surgery and Chemotherapy,10-05-2022,20-05-2022,Mizoram,2022,10,No,Recovered,4,No,25000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,980,68,Male,Hypertension,Medication and Counseling,28-02-2023,09-05-2023,Sikkim,2023,70,No,Stable,4,Yes,1000
980,981,45,Female,Appendicitis,Appendectomy,28-02-2024,10-05-2024,Andhra Pradesh,2024,72,No,Recovered,3,No,8000
981,982,40,Male,Fractured Leg,Cast and Physical Therapy,20-02-2025,03-05-2025,Puducherry,2025,72,No,Recovered,4,No,3000
982,983,78,Female,Heart Attack,Cardiac Catheterization,07-09-2024,20-11-2024,Punjab,2024,74,Yes,Stable,2,Yes,18000
983,984,25,Male,Allergic Reaction,Epinephrine Injection,30-11-2022,06-02-2023,Kerala,2022,68,No,Recovered,5,No,100

In [18]:
df.isnull().sum()

patient_id           0
age                  0
gender               0
condition            0
medication           0
admission_date       0
discharge_date       0
patient_state        0
year_of_admission    0
length_of_stay       0
readmission          0
outcome              0
satisfaction         0
insurance_claimed    0
total_cost           0
dtype: int64

In [23]:
#Date formatting
df['admission_date'] = pd.to_datetime(df['admission_date'], dayfirst=True)
df['discharge_date'] = pd.to_datetime(df['discharge_date'], dayfirst=True)

In [26]:
#validation
invalid_dates = df[df['discharge_date'] < df['admission_date']]
invalid_dates.shape

(0, 15)

In [28]:
df['calculated_los'] = (df['discharge_date'] - df['admission_date']).dt.days
(df['calculated_los'] == df['length_of_stay']).value_counts()

True    984
Name: count, dtype: int64

In [29]:
df['length_of_stay'] = df['calculated_los']
df.drop(columns='calculated_los', inplace=True)

In [30]:
df[['age', 'length_of_stay', 'total_cost', 'satisfaction']].describe()

              age  length_of_stay    total_cost  satisfaction
count  984.000000      984.000000    984.000000    984.000000
mean    53.754065       37.663618   8367.479675      3.598577
std     14.941135       19.595805   7761.990976      0.883002
min     25.000000        1.000000    100.000000      2.000000
25%     45.000000       21.000000   1000.000000      3.000000
50%     55.000000       38.000000   6000.000000      4.000000
75%     65.000000       54.250000  15000.000000      4.000000
max     78.000000       76.000000  25000.000000      5.000000

In [ ]:
#Feature Engineering

In [32]:
#Age Group
def age_group(age):
    if age < 18:
        return 'Child'
    elif age < 60:
        return 'Adult'
    else:
        return 'Elderly'

df['age_group'] = df['age'].apply(age_group)

In [33]:
#Stay Category
df['stay_category'] = pd.cut(
    df['length_of_stay'],
    bins=[-1, 3, 7, 1000],
    labels=['Short Stay', 'Medium Stay', 'Long Stay']
)

In [34]:
#Admission Year
df['admission_year'] = df['admission_date'].dt.year

In [35]:
df[['age_group', 'stay_category', 'admission_year']].value_counts().head()#Validate engineered features

age_group  stay_category  admission_year
Adult      Long Stay      2022              146
                          2023              144
                          2024              136
                          2025              128
Elderly    Long Stay      2023              101
Name: count, dtype: int64

In [36]:
df['stay_category'].value_counts()

stay_category
Long Stay      931
Medium Stay     41
Short Stay      12
Name: count, dtype: int64

In [41]:
df.to_csv("hospital_patient_final.csv", index=False)#saved the final